// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { Hash, AccountId32Like } from "dedot/codecs";
import type {
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  ConstructorCallOptions,
  ContractInstantiateResult,
} from "dedot/contracts";

export interface ConstructorQuery<ChainApi extends GenericSubstrateApi>
  extends GenericConstructorQuery<ChainApi> {
  /**
   * Constructor that initializes the `bool` value to the given `init_value`.
   *
   * @param {Hash} spaceCode
   * @param {AccountId32Like} ownerId
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorQueryCall<
    ChainApi,
    (
      spaceCode: Hash,
      ownerId: AccountId32Like,
      options: ConstructorCallOptions,
    ) => Promise<ContractInstantiateResult<ChainApi>>
  >;
}
