// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { Hash, AccountId32Like } from "dedot/codecs";
import type {
  GenericConstructorTx,
  GenericConstructorTxCall,
  ConstructorTxOptions,
  GenericInstantiateSubmittableExtrinsic,
} from "dedot/contracts";

export interface ConstructorTx<ChainApi extends GenericSubstrateApi>
  extends GenericConstructorTx<ChainApi> {
  /**
   * Constructor that initializes the `bool` value to the given `init_value`.
   *
   * @param {Hash} spaceCode
   * @param {AccountId32Like} ownerId
   * @param {ConstructorTxOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorTxCall<
    ChainApi,
    (
      spaceCode: Hash,
      ownerId: AccountId32Like,
      options: ConstructorTxOptions,
    ) => GenericInstantiateSubmittableExtrinsic<ChainApi>
  >;
}
