// Generated by dedot cli

import type { AccountId32 } from "dedot/codecs";

export type InkPrimitivesLangError = "CouldNotReadInput";

export type MotherspaceError =
  | { tag: "Custom"; value: string }
  | { tag: "UnAuthorized" }
  | { tag: "SpaceNotFound" }
  | { tag: "PluginNotFound" }
  | { tag: "PluginLaunchFailed" }
  | { tag: "PluginIdExisted" };

export type MotherspaceSpaceInfo = {
  name: string;
  desc?: string | undefined;
  logo?: MotherspaceImageSource | undefined;
};

export type MotherspaceImageSource =
  | { tag: "IpfsCid"; value: string }
  | { tag: "Url"; value: string };

export type MotherspaceSpaceConfig = {
  registration: MotherspaceRegistrationType;
  pricing: MotherspacePricing;
};

export type MotherspaceRegistrationType =
  | "PayToJoin"
  | "RequestToJoin"
  | "InviteOnly";

export type MotherspacePricing =
  | { tag: "Free" }
  | { tag: "OneTimePaid"; value: bigint }
  | { tag: "Subscription"; value: [bigint, number] };

export type MotherspacePagination = {
  items: Array<AccountId32>;
  from: number;
  perPage: number;
  hasNextPage: boolean;
  total: number;
};

export type InkEnvNoChainExtension = null;
