// Generated by dedot cli

import type { VersionedGenericSubstrateApi, RpcVersion } from "dedot/types";
import type { GenericContractApi } from "dedot/contracts";
import type { SubstrateApi } from "dedot/chaintypes";
import { ContractQuery } from "./query";
import { ContractTx } from "./tx";
import { ConstructorQuery } from "./constructor-query";
import { ConstructorTx } from "./constructor-tx";

export interface Psp34NftContractApi<
  ChainApi extends VersionedGenericSubstrateApi = SubstrateApi,
> extends GenericContractApi<ChainApi> {
  query: ContractQuery<ChainApi[RpcVersion]>;
  tx: ContractTx<ChainApi[RpcVersion]>;
  constructorQuery: ConstructorQuery<ChainApi[RpcVersion]>;
  constructorTx: ConstructorTx<ChainApi[RpcVersion]>;
}
